export const risks = [
    "Arranjo físico inadequado",
    "Atmosferas explosivas",
    "Bacilos",
    "Bactérias",
    "Controle rígido de produtividade",
    "Esforço físico excessivo",
    "Ferramentas e iluminação inapropriadas",
    "Frio",
    "Fumos",
    "Fungos",
    "Gases",
    "Iluminação inadequada",
    "Jornadas de trabalho extensas",
    "Levantamento e transporte de peso",
    "Máquinas e equipamentos sem proteção",
    "Monotonia e repetitividade",
    "Névoas",
    "Neblinas",
    "Poeiras",
    "Postura inadequada",
    "Pressões anormais",
    "Protozoários",
    "Radiações ionizantes",
    "Radiações não ionizantes",
    "Risco de choque elétrico",
    "Risco de incêndio",
    "Ruídos",
    "Substâncias, compostos ou produtos químicos",
    "Umidade",
    "Vapores",
    "Vibrações",
    "Vírus",
    "Animais peçonhentos"
];